services:
  mysqldbblog:
    container_name: mysqlcontainerforblog
    image: mysql:8.0.28
    platform: linux/amd64
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3304:3306
    environment:
      MYSQL_DATABASE: mydbblog
      MYSQL_USER: admin
      MYSQL_PASSWORD: takemyhand
      MYSQL_ROOT_PASSWORD: takemyhand
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge

volumes:
  mysql_data:
