spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3304/mydbblog
    username: admin
    password: takemyhand
  jpa:
    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8085
  servlet:
    context-path: /api-stg

